version: '3.7'

services:
  app:
    container_name: front
    command: npm start
    build: ./
    environment:
        NODE_ENV: "development"
        CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./www:/var/www
    ports:
      - ${PORT}:3000
