version: '3.7'

services:

  app:
    container_name: front
    command: npm start
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
        NODE_ENV: "development"
        CHOKIDAR_USEPOLLING: "true"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4001:3000
